import type { Metadata } from "next";
import "bootstrap-icons/font/bootstrap-icons.css";
import "./globals.scss";
import ExtraRootLayout from "@/components/layouts/extraRootLayout/ExtraRootLayout";
import { geistMono, geistSans } from "@/utils/fonts/LocalFonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ExtraRootLayout>{children}</ExtraRootLayout>
      </body>
    </html>
  );
}
